/* Safari Golf Tour — full course information.
 * `short` is the film-title name on the cover; `cover` is the aerial photograph (Unsplash id).
 * Lengths are back-tee approximations for planning, confirmed with the club at booking.
 * Loaded after js/places.js, before js/site.js.
 */
(function () {
  "use strict";
  var S = window.SGT;

  var INFO = {
    karen: { length: 6900, founded: 1937, altitude: "1,800 m", greens: "Bent grass, kikuyu fairways", signature: "The 12th, a long par 4 that turns through a stand of indigenous trees to a green sitting beneath the Ngong Hills.", story: "Laid out on part of Karen Blixen's old coffee estate, the course keeps the plantation's mature trees and its sense of distance from the city. At altitude the ball flies ten per cent further, which flatters the drive and punishes the approach.", caddies: "Caddies compulsory and excellent", carts: "Carts available, walking encouraged", handicap: "28 men, 36 women", dress: "Collared shirts, tailored shorts, soft spikes", best: "Jan – Mar, Jun – Oct" },
    muthaiga: { length: 6560, founded: 1913, altitude: "1,700 m", greens: "Bent grass", signature: "The short par-4 2nd, where a stream crosses the fairway twice and the green is guarded by a single ancient fig.", story: "Kenya's oldest club and the home of the Kenya Open until 2019. Narrow, mature and fiercely protected by its trees; a course that rewards position over power and has humbled better players than most of us.", caddies: "Caddies compulsory", carts: "Limited; walking course", handicap: "24 men, 30 women; guests of members or by arrangement", dress: "Strict: collars, no cargo shorts, no mobiles on the course", best: "Jan – Mar, Jun – Oct" },
    windsor: { length: 6900, founded: 1992, altitude: "1,800 m", greens: "Bent grass", signature: "The 18th, a dog-leg par 5 through the forest to a green in front of the Victorian clubhouse.", story: "Carved through indigenous forest on the north side of Nairobi, with colobus monkeys in the canopy and fairways that stay green through the dry season. The hotel beside the first tee makes it the natural last round before an evening flight.", caddies: "Caddies available", carts: "Carts available", handicap: "36", dress: "Collared shirts, soft spikes", best: "Year round; Jan – Mar driest" },
    vipingo: { length: 7255, founded: 2010, altitude: "Sea level", greens: "Paspalum", signature: "The 9th on the Baobab Course, a par 3 played off a ridge towards the Indian Ocean with the trade wind in your face.", story: "The Baobab Course is the only PGA-accredited layout in East Africa, set on a ridge north of Mombasa with the ocean on the horizon from nearly every hole. Built for the heat, with wide corridors, paspalum turf and a breeze that arrives after lunch.", caddies: "Caddies available", carts: "Carts included", handicap: "36", dress: "Resort dress code", best: "Oct – Mar" },
    "rift-valley": { length: 6800, founded: 2001, altitude: "2,100 m", greens: "Kikuyu and bent", signature: "The 5th, a downhill par 4 with the whole of Lake Naivasha below the green.", story: "The highest course on our list, set on the escarpment above Lake Naivasha. Zebra and giraffe graze the rough, and the thin air adds thirty yards to a well-struck drive. The lodge sits on the 1st tee.", caddies: "Caddies included", carts: "Carts available; hilly", handicap: "36", dress: "Relaxed; collars preferred", best: "Jun – Oct, Jan – Feb" },
    kili: { length: 7060, founded: 2012, altitude: "1,400 m", greens: "Bent grass", signature: "The par-5 18th, played straight at Kilimanjaro with zebra on the fairway and the clubhouse behind the green.", story: "Set on a private wildlife estate between Arusha and the mountain. David Jones routed the holes so that the mountain appears behind five greens; the wildebeest and zebra do as they please. The course opens most of our Tanzania journeys.", caddies: "Caddies included", carts: "Carts available", handicap: "36", dress: "Collared shirts, soft spikes", best: "Jun – Oct, Dec – Feb" },
    "sea-cliff": { length: 3100, founded: 2009, altitude: "Sea level", greens: "Paspalum", signature: "The 7th, a short par 4 along the cliff with the reef below and the mangroves on the left.", story: "Nine ocean-side holes on Zanzibar's north-west coast, designed by Peter Matkovich for a resort course that is more fun than it has any right to be. Play it twice before lunch and the beach after.", caddies: "Caddies available", carts: "Carts included", handicap: "None", dress: "Resort dress code", best: "Jun – Oct, Dec – Feb" },
    "fancourt-links": { length: 7290, founded: 2000, altitude: "200 m", greens: "Bent grass, fescue fairways", signature: "The par-3 17th, played over a burn to a green ringed by pot bunkers, the hole Ernie Els and Tiger Woods halved in the 2003 Presidents Cup.", story: "Gary Player's answer to the question of whether a links can be built on a flat field: 700,000 cubic metres of earth moved to make dunes, hollows and a routing that changes direction with every hole. Ranked number one in South Africa since it opened, and played walking with a caddie, as it should be.", caddies: "Caddies compulsory and included", carts: "No carts; walking only", handicap: "24 men, 30 women", dress: "Strict club dress code", best: "Mar – May, Sep – Nov" },
    "fancourt-montagu": { length: 7150, founded: 1992, altitude: "200 m", greens: "Bent grass", signature: "The par-5 2nd, a double dog-leg with water at the green that sets the tone for the round.", story: "The original Fancourt course, refined by David McLay Kidd into a parkland that sits comfortably among the country's top five. Softer than the Links, with the Outeniqua mountains behind every green and water on half the holes.", caddies: "Caddies available", carts: "Carts included", handicap: "28 men, 36 women", dress: "Club dress code", best: "Mar – May, Sep – Nov" },
    "fancourt-outeniqua": { length: 6900, founded: 1994, altitude: "200 m", greens: "Bent grass", signature: "The 16th, a short par 4 with the lake on the right and a green that asks for one more club.", story: "The friendliest of Fancourt's three, with wide fairways and water on ten holes. The round to play on arrival day, when the clubs have just come out of the case.", caddies: "Caddies available", carts: "Carts included", handicap: "36", dress: "Club dress code", best: "Mar – May, Sep – Nov" },
    "pearl-valley": { length: 7296, founded: 2003, altitude: "150 m", greens: "Bent grass", signature: "The 18th, a par 4 with the Berg River on the left and the Simonsberg filling the sky behind the green.", story: "A Jack Nicklaus signature course among the Paarl vineyards and the host of three South African Opens. Big, generous and beautifully kept, with the mountains close enough to touch and a wine farm at the clubhouse door.", caddies: "Caddies available", carts: "Carts included", handicap: "36", dress: "Collared shirts, soft spikes", best: "Oct – Apr" },
    "leopard-creek": { length: 7300, founded: 1996, altitude: "200 m", greens: "Bent grass", signature: "The par-5 13th along the Crocodile River, where the green sits above a bend in the water and the Kruger elephants cross the far bank.", story: "Gary Player's bushveld masterpiece on the southern boundary of Kruger. A private club that we open by invitation, with hippos below the 13th, crocodiles sunning on the bank and a halfway house that looks into the park. Host of the Alfred Dunhill Championship.", caddies: "Caddies compulsory and included", carts: "Carts available", handicap: "24 men, 30 women", dress: "Strict club dress code", best: "Apr – Oct" },
    skukuza: { length: 6300, founded: 1972, altitude: "260 m", greens: "Kikuyu", signature: "The 9th, a par 4 along the Lake Panic dam with hippos in the water and a sign that reads 'beware of the animals'.", story: "The only unfenced course inside Kruger National Park, built for the park's staff and open to visitors by arrangement. Nine holes played twice, with impala on the fairway and a ranger walking the round. Not a championship test, and one of the most memorable rounds in the world.", caddies: "None; ranger escort included", carts: "Carts available", handicap: "None", dress: "Relaxed", best: "Apr – Oct" },
    arabella: { length: 6800, founded: 1999, altitude: "Sea level", greens: "Bent grass", signature: "The par-5 8th along the Bot River lagoon, with the Kogelberg mountains across the water.", story: "An hour from Cape Town on the Bot River lagoon, with the back nine running along the water and a finish that is among the best in the country. The hotel sits on the course, which makes an early tee time easy.", caddies: "Caddies available", carts: "Carts included", handicap: "36", dress: "Collared shirts, soft spikes", best: "Oct – Apr" },
    erinvale: { length: 6850, founded: 1995, altitude: "100 m", greens: "Bent grass", signature: "The 10th, played straight uphill towards the Helderberg with the whole of False Bay at your back.", story: "Gary Player's Winelands course at the foot of the Helderberg, host of the 1996 World Cup of Golf. A front nine on the flat and a back nine that climbs into the mountain, with views of the bay from the top.", caddies: "Caddies available", carts: "Carts included", handicap: "36", dress: "Collared shirts", best: "Oct – Apr" },
    "elephant-hills": { length: 6900, founded: 1974, altitude: "900 m", greens: "Kikuyu", signature: "The 15th, where the spray of the Falls rises above the trees behind the green.", story: "Ten minutes from Victoria Falls, with warthogs rooting in the rough, impala on the fairways and the Zambezi beside the back nine. The only course in the world where you can see the spray of a natural wonder from the tee.", caddies: "Caddies included", carts: "Carts available", handicap: "None", dress: "Relaxed; collars preferred", best: "May – Oct" },
    borrowdale: { length: 6900, founded: 1998, altitude: "1,500 m", greens: "Bent grass", signature: "The par-3 12th over a rock-ringed pond, the postcard hole.", story: "Harare's championship estate course, designed by Peter Matkovich among granite kopjes and msasa woodland. The round for guests routing through the capital on the way to Mana Pools.", caddies: "Caddies available", carts: "Carts available", handicap: "36", dress: "Collared shirts", best: "Apr – Oct" },
    "heritage-chateau": { length: 7085, founded: 2004, altitude: "Sea level", greens: "Bermuda", signature: "The par-5 7th, with the lagoon beyond the green and the whole Bel Ombre estate below.", story: "The home of the AfrAsia Bank Mauritius Open on the DP World Tour, on the Bel Ombre estate in the island's south. The Indian Ocean is visible from every hole; the Black River mountains frame the inland holes. Play it in October when the greens are at tournament speed.", caddies: "Caddies available", carts: "Carts included", handicap: "36", dress: "Resort dress code", best: "May – Nov" },
    "heritage-reserve": { length: 6500, founded: 2023, altitude: "100 m", greens: "Bermuda", signature: "The 16th, a short par 4 played downhill towards the lagoon with the ocean filling the view.", story: "Opened in 2023 in the hills above Le Château, designed by Peter Matkovich with Louis Oosthuizen. Shorter, hillier and more about shot-making than its sibling, with the best views on the island.", caddies: "Caddies available", carts: "Carts included", handicap: "36", dress: "Resort dress code", best: "May – Nov" },
    "ile-aux-cerfs": { length: 7000, founded: 2003, altitude: "Sea level", greens: "Paspalum", signature: "The 9th, a par 4 along the lagoon with volcanic rock and the mountains of the east coast across the water.", story: "Bernhard Langer's island course, reached by boat from the Touessrok jetty, with the lagoon in play on nine holes and a volcanic-rock garden where other courses have rough. Lunch at the beach club afterwards is part of the round.", caddies: "Caddies available", carts: "Carts included", handicap: "36", dress: "Resort dress code", best: "May – Nov" },
    anahita: { length: 7000, founded: 2008, altitude: "Sea level", greens: "Paspalum", signature: "The 6th, a par 3 across the ocean's edge with Ile aux Cerfs on the horizon.", story: "Ernie Els' east-coast course, with six holes along the ocean and the rest among the mangroves and sugar fields. Quieter than its neighbour across the water, and in better condition than almost anything on the island.", caddies: "Caddies available", carts: "Carts included", handicap: "36", dress: "Resort dress code", best: "May – Nov" },
    entebbe: { length: 6600, founded: 1901, altitude: "1,150 m", greens: "Bermuda", signature: "The 10th, a par 4 along the lake shore with the marabou storks in the trees.", story: "East Africa's oldest course, on the shore of Lake Victoria a short walk from the hotel. A gentle, mature parkland where the vervet monkeys steal balls and the storks ignore everyone. The round before the flight to Bwindi.", caddies: "Caddies included", carts: "Few; walking course", handicap: "None", dress: "Relaxed; collars preferred", best: "Jun – Sep, Dec – Feb" },
    "uganda-gc": { length: 6800, founded: 1908, altitude: "1,200 m", greens: "Bermuda", signature: "The 5th, a long par 4 across the Kitante stream to a raised green in the middle of the city.", story: "Host of the Uganda Open in the centre of Kampala, with a stream that crosses eight fairways and a hill that makes the back nine feel longer than its card. An optional round for those with a night in the capital.", caddies: "Caddies included", carts: "Few; walking course", handicap: "None", dress: "Collared shirts", best: "Jun – Sep, Dec – Feb" },
    kigali: { length: 7000, founded: 2022, altitude: "1,500 m", greens: "Bent grass", signature: "The par-3 14th over a ravine to a green cut into the hillside.", story: "Rebuilt by Gary Player Design from the old Nyarutarama course into the best-conditioned layout in East Africa, ten minutes from the city centre. Rolling, well bunkered and built for championship play, with the thousand hills as the backdrop.", caddies: "Caddies included", carts: "Carts available; hilly", handicap: "36", dress: "Collared shirts, soft spikes", best: "Jun – Sep, Dec – Feb" },
    phakalane: { length: 7000, founded: 1997, altitude: "1,000 m", greens: "Bent grass", signature: "The 17th, a par 5 with water down the left and the clubhouse behind the green.", story: "Gaborone's championship course, designed by Peter Matkovich on the edge of the city with lakes on eight holes. The round for guests routing through the capital before the Delta.", caddies: "Caddies available", carts: "Carts included", handicap: "36", dress: "Collared shirts", best: "Apr – Oct" },
    livingstone: { length: 6700, founded: 1908, altitude: "1,000 m", greens: "Kikuyu", signature: "The 6th, a par 4 where the zebra graze between the tee and the fairway bunkers.", story: "Ten minutes from the Zambian side of the Falls, with zebra and impala on the fairways and a colonial clubhouse that has not changed in decades. The course is simple; the setting is not.", caddies: "Caddies included", carts: "Carts available", handicap: "None", dress: "Relaxed", best: "May – Oct" },
    lusaka: { length: 6900, founded: 1933, altitude: "1,250 m", greens: "Bent grass", signature: "The 18th, a long par 4 to a green beneath the old clubhouse.", story: "Host of the Zambia Open, a mature parkland course on the way to the Lower Zambezi with jacaranda-lined fairways and fast, true greens. Busy at weekends; we book weekday mornings.", caddies: "Caddies included", carts: "Carts available", handicap: "36", dress: "Collared shirts", best: "Apr – Oct" },
    windhoek: { length: 6700, founded: 1926, altitude: "1,650 m", greens: "Bent grass", signature: "The 11th, a par 3 played from an elevated tee towards the Auas mountains.", story: "The capital's championship course on the edge of the Khomas highlands, with the thin air of 1,650 metres adding length and the mountains on the skyline. The opening round before the drive to Sossusvlei.", caddies: "Caddies available", carts: "Carts included", handicap: "36", dress: "Collared shirts", best: "Apr – Oct" },
    rossmund: { length: 6700, founded: 1991, altitude: "Sea level", greens: "Bent grass", signature: "The 8th, a par 4 cut between two dunes with the Namib on both sides and the Atlantic fog rolling in.", story: "One of only a handful of true desert courses in the world: green fairways cut into the Namib dunes beside the Swakop River, with springbok on the practice ground and the sea fog as a morning hazard. Nothing else in Africa plays like it.", caddies: "Caddies available", carts: "Carts included", handicap: "None", dress: "Relaxed", best: "Apr – Oct" },
    "royal-marrakech": { length: 6600, founded: 1923, altitude: "450 m", greens: "Bent grass", signature: "The 7th on the old course, a par 4 between cypress and olive with the snow of the Atlas behind the green.", story: "The oldest course in the south, laid out under the Pasha of Marrakech in 1923 and extended to 27 holes. Narrow corridors of cypress, palm, olive and orange trees, with the Atlas on the skyline from the back tees. Churchill and Eisenhower both played here.", caddies: "Caddies included", carts: "Carts available", handicap: "36", dress: "Collared shirts, soft spikes", best: "Oct – May" },
    assoufid: { length: 7000, founded: 2013, altitude: "550 m", greens: "Bent grass", signature: "The par-3 12th, played across a dry wadi to a green with the whole Atlas range behind it.", story: "Niall Cameron's desert course in the foothills above the Agafay, fifteen minutes from the medina and regularly ranked the best course in Morocco. Firm, fast and natural, with the mountains filling the view from every tee.", caddies: "Caddies included", carts: "Carts included", handicap: "36", dress: "Collared shirts, soft spikes", best: "Oct – May" },
    "al-maaden": { length: 6900, founded: 2009, altitude: "450 m", greens: "Bent grass", signature: "The 18th, a par 4 along the water to a green beside the sculpture garden.", story: "Kyle Phillips' course ten minutes from the city, with contemporary sculpture set among the water features and a clubhouse built like a riad. Easy on the body and the eye: the round for arrival day.", caddies: "Caddies included", carts: "Carts included", handicap: "36", dress: "Collared shirts", best: "Oct – May" },
    "dar-es-salam": { length: 7300, founded: 1971, altitude: "100 m", greens: "Bent grass", signature: "The 9th on the Red Course, a par 3 to an island green in a lake full of water lilies.", story: "Robert Trent Jones Sr.'s Red Course in Rabat's cork-oak forest is the country's championship test and the home of the Hassan II Trophy and the Lalla Meryem Cup. Long, tree-lined and immaculate, with 45 holes on the estate in all.", caddies: "Caddies included", carts: "Carts available", handicap: "28 men, 36 women", dress: "Strict club dress code", best: "Oct – May" },
    mazagan: { length: 7400, founded: 2009, altitude: "Sea level", greens: "Paspalum", signature: "The 15th, a par 4 along the Atlantic with the beach on the left and the wind doing what it likes.", story: "Gary Player's links-style course on the dunes at El Jadida, an hour south of Casablanca, with the ocean on one side and the resort on the other. Wide, firm and windy: a links in all but the turf.", caddies: "Caddies available", carts: "Carts included", handicap: "36", dress: "Resort dress code", best: "Mar – Nov" },
    tazegzout: { length: 7000, founded: 2014, altitude: "50 m", greens: "Bermuda", signature: "The 11th, a par 3 across a ravine on the cliff edge with the surf of Taghazout below.", story: "Kyle Phillips' clifftop course north of Agadir, with argan trees between the fairways and the Atlantic beneath the greens. The best coastal round in the country and the reason to add Taghazout to a Marrakech trip.", caddies: "Caddies included", carts: "Carts included", handicap: "36", dress: "Collared shirts", best: "Oct – May" },
    michlifen: { length: 7000, founded: 2014, altitude: "1,650 m", greens: "Bent grass", signature: "The 6th, a par 5 through the cedars with Barbary macaques watching from the trees.", story: "Jack Nicklaus Design's course among the cedar forests of Ifrane in the Middle Atlas, at 1,650 metres. Cool, green and alpine, with snow on the greens in January and the macaques of the national park on the fairway edges.", caddies: "Caddies included", carts: "Carts included", handicap: "36", dress: "Collared shirts", best: "Apr – Oct" },
    "golf-du-rova": { length: 6400, founded: 1951, altitude: "1,300 m", greens: "Kikuyu", signature: "The 14th, a par 4 along a ridge with the rice terraces of the highlands below.", story: "The country's only eighteen, on the rolling hills of Andakana twenty kilometres from Antananarivo. Undulating and natural, with a small hotel at the clubhouse for the night before the forest. Sources differ on the par; the club's card is the one we use.", caddies: "Caddies included", carts: "Few; walking course", handicap: "None", dress: "Relaxed", best: "Apr – Nov" },
    avlekete: { length: 7300, founded: 2026, altitude: "Sea level", greens: "Paspalum", signature: "The 16th, a par 5 between the lagoon and the Atlantic with the sacred grove on the left.", story: "Benin's first eighteen-hole course, routed by Jeremy Pern between the lagoon and the Atlantic west of Cotonou around protected trees and a sacred grove. Long and open, with four par 3s, four par 5s and the ocean wind. We confirm tee times at booking while it settles in." , caddies: "Caddies available", carts: "Carts included", handicap: "None", dress: "Collared shirts", best: "Nov – Apr" }
  };

  /* Film-title name and aerial cover for every course. */
  var COVER = {
    karen: ["Karen", "1742498626135-67a7d3501eff"],
    muthaiga: ["Muthaiga", "1700667315229-070498867aea"],
    windsor: ["Windsor", "1700667315267-6565aaca50c1"],
    vipingo: ["Vipingo", "1716389089405-9109acb30533"],
    "rift-valley": ["Rift Valley", "1610944864046-4f0de0e667d0"],
    kili: ["Kilimanjaro", "1677137867878-a2b527e4c7fc"],
    "sea-cliff": ["Sea Cliff", "1786398536809-a3956f453523"],
    "fancourt-links": ["The Links", "1626512296443-2dbcaa240c49"],
    "fancourt-montagu": ["Montagu", "1593331228867-e2a635f4b1cc"],
    "fancourt-outeniqua": ["Outeniqua", "1720446548662-6845735ba69d"],
    "pearl-valley": ["Pearl Valley", "1613754627343-622ea791af6e"],
    "leopard-creek": ["Leopard Creek", "1605144156683-5ebde77feed5"],
    skukuza: ["Skukuza", "1605147863013-dea22add791e"],
    arabella: ["Arabella", "1605144156698-804de50de0ca"],
    erinvale: ["Erinvale", "1627742259845-912f536ef00a"],
    "elephant-hills": ["Elephant Hills", "1605147861225-7bcd55f8e513"],
    borrowdale: ["Borrowdale", "1776723670848-adf761b4bbcc"],
    "heritage-chateau": ["Le Château", "1769442871876-a370ee075a54"],
    "heritage-reserve": ["La Réserve", "1591468309810-02eace4bf2f0"],
    "ile-aux-cerfs": ["Ile aux Cerfs", "1692087224072-83f25202ca4a"],
    anahita: ["Anahita", "1646204221936-35451c74e3de"],
    entebbe: ["Entebbe", "1605144884914-64023214bdca"],
    "uganda-gc": ["Kampala", "1776802405398-a52677e55aa2"],
    kigali: ["Kigali", "1516705416642-fa4f130a0bb3"],
    phakalane: ["Phakalane", "1689592607829-43321b3fcc55"],
    livingstone: ["Livingstone", "1776723670814-6f786c205117"],
    lusaka: ["Lusaka", "1776717163995-7807586c229b"],
    windhoek: ["Windhoek", "1585839985872-b26117e60ea2"],
    rossmund: ["Rossmund", "1694636507260-8b2428e3b738"],
    "royal-marrakech": ["Marrakech", "1580758852857-a243f4de9cc7"],
    assoufid: ["Assoufid", "1605144156546-91acf5e4cffd"],
    "al-maaden": ["Al Maaden", "1605144884374-ecbb643615f6"],
    "dar-es-salam": ["Dar Es Salam", "1700667315345-e0c51587b2fd"],
    mazagan: ["Mazagan", "1700667315305-ef2a027f9078"],
    tazegzout: ["Tazegzout", "1687730824562-bcee4645bd15"],
    michlifen: ["Michlifen", "1677138055562-483b824b6348"],
    "golf-du-rova": ["Rova", "1788244160501-b4830945f988"],
    avlekete: ["Ouidah", "1775686318424-9987122d8402"]
  };

  S.COURSES.forEach(function (c) {
    var i = INFO[c.id];
    if (i) Object.keys(i).forEach(function (k) { c[k] = i[k]; });
    var v = COVER[c.id];
    c.short = v ? v[0] : c.name.replace(/ (Golf|Country|Club|Resort|Estate|&).*$/, "");
    if (v) { c.cover = v[1]; c.photo = v[1]; }
  });
  S.COURSE_INFO = INFO;
})();
