/* Safari Golf Tour — countries, national parks and reserves, extra courses, and the trip builder's rates.
 * Loaded after js/content.js, before js/site.js.
 */
(function () {
  "use strict";
  var S = window.SGT;

  Object.assign(S.PHOTO, {
    gorilla: "1614528767034-70de9fe166e0", gorillaFamily: "1722291731448-3afe029611a6", gorillaSilver: "1581281863883-2469417a1668",
    vicFallsSunset: "1618811308896-d279d72fdf4d", vicFalls: "1627347456206-d3df7d8484b0", vicFallsGorge: "1759159160662-256485d830d8",
    vicBridge: "1634179412263-19d96377c1a2", fallsRainbow: "1603201236596-eb1a63eb0ede",
    okavangoAerial: "1722645148077-a7f99c8bcef2", okavangoHippos: "1590214780567-b48c7c927b7c", elephantWater: "1653900217156-77a588505248",
    elephantReeds: "1697638332749-da3ba4046082", sunsetWater: "1573707627676-eda00266adce", mokoro: "1635749687861-4341928cbf97",
    sossusvlei: "1613155358090-7365a34ed5ec", deadvlei: "1559160581-44bd4222d397", deadvlei2: "1696104613970-fc7f58d1ff39", dunes: "1652599720885-abf363ed2992",
    cheetah: "1624958319297-d1aa3a41378e", cheetahGold: "1551969014-7d2c4cddf0b6", cheetahRun: "1498056523130-b76aa40137b0", cheetahClose: "1569600428323-7fd18782b483",
    rhino: "1598894000396-bc30e0996899", rhinoPair: "1612703252506-e2f1f674752d", rhinoBlack: "1535082427395-4a20c7c7af88",
    crossing: "1564101160531-4838e8a5f4e7", herd: "1518459384564-ecfd8e80721f", crossing2: "1647776006651-1e5230db330c", crossing3: "1729708309658-929aadd7d75e",
    etoshaZebra: "1545833303-6bab33314c69", etoshaGiraffe: "1588508106682-29dcfe09f50b", etoshaElephant: "1589798798923-fd59f00c50d7",
    etoshaPan: "1667389865345-e2e7c8344b00", lionPairGrass: "1596220025211-df3289d602ac", lioness: "1596227027532-32d431e88671", loneTree: "1699896532047-3a445b64811e",
    hippo: "1562426772-f7b1d159764b", hippoSunset: "1705312148583-493bf8fe6b3b", hippos: "1706616172847-7a0a33972b27", hipposGrass: "1671931637948-e3a4bfa571c7",
    flamingos: "1760930019635-0d14cbfa6e83", flamingos2: "1702125609002-6eb8ac3295da",
    baobabs: "1558694440-03ade9215d7b", baobabAvenue: "1570742544137-3a469196c32b", baobabSunset: "1585335740623-f7a1f0c446eb",
    zambeziElephant: "1533631278779-d722ded4c7df", zambeziSunset: "1598338332181-c7a78afa1198", zambeziBank: "1623000015590-b29a22ec1f34", zambeziBoat: "1721418582804-95473ab2b4d0"
  });

  /* ---------- Countries ---------- */
  S.COUNTRIES = [
    { id: "kenya", name: "Kenya", region: "East Africa", gateway: "Nairobi (NBO)", bestMonths: "Jul – Oct, Jan – Feb", photo: "g_caddie",
      strap: "The original safari country, with golf that goes back a century.",
      intro: "Three championship courses inside forty minutes of each other in Nairobi, and the Mara conservancies an hour's flight away. The easiest place in Africa to alternate a round and a game drive without wasting a day.",
      journeys: ["kenya-classic", "grand-crossing"] },
    { id: "tanzania", name: "Tanzania", region: "East Africa", gateway: "Kilimanjaro (JRO)", bestMonths: "Jun – Oct, Dec – Mar", photo: "kilimanjaro",
      strap: "The Serengeti, the Crater, and one superb course beneath the mountain.",
      intro: "Safari at its most vast. Kilimanjaro Golf opens the trip, then wildlife on a scale nowhere else can match, finished with a descent into the Ngorongoro Crater. Zanzibar adds nine ocean-side holes and a beach.",
      journeys: ["tanzania-grand"] },
    { id: "uganda", name: "Uganda", region: "East Africa", gateway: "Entebbe (EBB)", bestMonths: "Jun – Sep, Dec – Feb", photo: "gorillaFamily",
      strap: "Gorillas in the forest, golf on the shore of Lake Victoria.",
      intro: "East Africa's oldest course beside the lake, then the single most affecting hour in travel with a mountain gorilla family in Bwindi. Works on its own or as a three-night addition to Kenya.",
      journeys: ["uganda-short-break"] },
    { id: "rwanda", name: "Rwanda", region: "East Africa", gateway: "Kigali (KGL)", bestMonths: "Jun – Sep, Dec – Feb", photo: "gorilla",
      strap: "The gentlest gorilla trek, and a Player-designed course in the capital.",
      intro: "Volcanoes National Park is two hours from Kigali on good roads, and Kigali Golf Resort is the best-conditioned course in East Africa. Akagera adds a classic savanna safari a short drive east.",
      journeys: [] },
    { id: "south-africa", name: "South Africa", region: "Southern Africa", gateway: "Cape Town (CPT) · Johannesburg (JNB)", bestMonths: "Mar – May, Sep – Nov", photo: "g_linksGold",
      strap: "The deepest golf on the continent, and the leopards of the Sabi Sand.",
      intro: "Fancourt, Pearl Valley and Leopard Creek would justify the flight on their own. Add the Winelands, the Garden Route and a private reserve on the Kruger boundary and you have the definitive first golf safari.",
      journeys: ["south-africa-signature", "grand-crossing", "mauritius-kruger"] },
    { id: "zimbabwe", name: "Zimbabwe", region: "Southern Africa", gateway: "Victoria Falls (VFA)", bestMonths: "May – Oct", photo: "vicFallsSunset",
      strap: "A round beside the Zambezi with the spray of the Falls on the horizon.",
      intro: "Elephant Hills is the only course in the world within sight of a natural wonder. Hwange and Mana Pools are among the wildest, least crowded parks in Africa, and the Falls themselves need no introduction.",
      journeys: ["victoria-falls-chobe", "grand-crossing"] },
    { id: "botswana", name: "Botswana", region: "Southern Africa", gateway: "Maun (MUB) · Kasane (BBK)", bestMonths: "May – Oct", photo: "okavangoAerial",
      strap: "The Okavango by mokoro, Chobe by boat, elephants by the thousand.",
      intro: "Botswana sells exclusivity: few vehicles, private concessions, and water-based safari that no other country offers. The golf is across the border at Victoria Falls, a ninety-minute transfer from Chobe.",
      journeys: ["victoria-falls-chobe"] },
    { id: "zambia", name: "Zambia", region: "Southern Africa", gateway: "Livingstone (LVI) · Lusaka (LUN)", bestMonths: "Jun – Oct", photo: "zambeziElephant",
      strap: "Walking safaris in the Luangwa, and golf on the Zambian side of the Falls.",
      intro: "South Luangwa invented the walking safari and still does it best. Livingstone has a championship course ten minutes from the Falls, and the Lower Zambezi offers canoeing among elephants.",
      journeys: [] },
    { id: "namibia", name: "Namibia", region: "Southern Africa", gateway: "Windhoek (WDH)", bestMonths: "May – Oct", photo: "sossusvlei",
      strap: "Desert golf, the dunes of Sossusvlei, and Etosha's floodlit waterholes.",
      intro: "The emptiest country on the list. Two courses, one in the capital and one in the dunes at Swakopmund, bracket a self-drive or fly-in safari through landscapes that look like nowhere else on earth.",
      journeys: [] },
    { id: "mauritius", name: "Mauritius", region: "Indian Ocean", gateway: "Mauritius (MRU)", bestMonths: "May – Oct", photo: "g_seaCourse",
      strap: "Tour-standard golf on an island, a short flight from the bush.",
      intro: "Host of the DP World Tour, with more championship golf per square mile than anywhere in Africa. Pairs naturally with Kruger for a bush-and-beach fortnight; the national park is small but worth a morning.",
      journeys: ["mauritius-kruger"] }
  ];

  /* ---------- Extra courses for the new countries ---------- */
  S.COURSES.push(
    { id: "kigali", name: "Kigali Golf Resort", country: "Rwanda", destination: "rwanda", designer: "Gary Player Design (2022)", par: 72, holes: 18, photo: "g_swingBack", note: "Rebuilt from the old Nyarutarama course into the best-conditioned layout in East Africa, ten minutes from the city centre." },
    { id: "phakalane", name: "Phakalane Golf Estate", country: "Botswana", destination: "botswana", designer: "Peter Matkovich", par: 72, holes: 18, photo: "g_swingBlue", note: "Gaborone's championship course, for guests routing through the capital before the Delta." },
    { id: "livingstone", name: "Livingstone Royal Golf Club", country: "Zambia", destination: "zambia", designer: "Founded 1908", par: 72, holes: 18, photo: "g_sunrise3", note: "Ten minutes from the Zambian side of the Falls, with zebra and impala on the fairways and a colonial clubhouse." },
    { id: "lusaka", name: "Lusaka Golf Club", country: "Zambia", destination: "zambia", designer: "Founded 1933", par: 72, holes: 18, photo: "g_crouch", note: "Host of the Zambia Open, a mature parkland course on the way to the Lower Zambezi." },
    { id: "windhoek", name: "Windhoek Golf & Country Club", country: "Namibia", destination: "namibia", designer: "Founded 1926", par: 72, holes: 18, photo: "g_trio", note: "The capital's championship course, on the edge of the Khomas highlands, and the opening round before Sossusvlei." },
    { id: "rossmund", name: "Rossmund Desert Golf Course", country: "Namibia", destination: "namibia", designer: "Swakopmund", par: 72, holes: 18, photo: "g_womanSunset", note: "One of only a handful of true desert courses in the world, green fairways cut into the Namib dunes beside the Swakop River." }
  );

  /* ---------- National parks and reserves ---------- */
  S.PARKS = [
    { id: "maasai-mara", name: "Maasai Mara & conservancies", country: "Kenya", countryId: "kenya", type: "National reserve", tier: "luxury", bestMonths: "Jul – Oct", photo: "crossing", wildlife: ["Great Migration", "Lion", "Leopard", "Cheetah"], nearest: { course: "karen", how: "45-minute flight from Nairobi Wilson" }, signature: "The river crossings, and the private conservancies where the cats are the point.", note: "Africa's most famous reserve. The private conservancies north of the river allow off-road tracking and night drives with a fraction of the vehicles." },
    { id: "amboseli", name: "Amboseli National Park", country: "Kenya", countryId: "kenya", type: "National park", tier: "premium", bestMonths: "Jun – Oct, Jan – Feb", photo: "kilimanjaro", wildlife: ["Elephant", "Kilimanjaro views", "Big tuskers"], nearest: { course: "karen", how: "40-minute flight or 4-hour drive from Nairobi" }, signature: "Big-tusked elephants beneath Kilimanjaro.", note: "The classic postcard of Africa: elephant herds crossing the plains with the mountain behind. Small, reliable and close to Nairobi." },
    { id: "laikipia", name: "Laikipia: Lewa & Ol Pejeta", country: "Kenya", countryId: "kenya", type: "Private conservancy", tier: "luxury", bestMonths: "Jun – Oct, Jan – Mar", photo: "rhinoPair", wildlife: ["Black & white rhino", "Grevy's zebra", "Chimpanzee sanctuary"], nearest: { course: "rift-valley", how: "1-hour flight from Nairobi" }, signature: "Walk with the rangers who protect the rhino.", note: "The conservancies of the Laikipia plateau hold the densest rhino populations in East Africa, with walking, horse-riding and night drives allowed." },
    { id: "lake-nakuru", name: "Lake Nakuru National Park", country: "Kenya", countryId: "kenya", type: "National park", tier: "premium", bestMonths: "Jun – Mar", photo: "flamingos", wildlife: ["Flamingo", "Rhino", "Rothschild's giraffe"], nearest: { course: "rift-valley", how: "1 hour from Great Rift Valley Lodge" }, signature: "Flamingos on the soda lake, rhino in the acacia forest.", note: "A compact Rift Valley park that pairs neatly with a round at Great Rift Valley Lodge on the drive from Nairobi." },
    { id: "samburu", name: "Samburu National Reserve", country: "Kenya", countryId: "kenya", type: "National reserve", tier: "premium", bestMonths: "Jun – Oct, Dec – Mar", photo: "giraffeClose", wildlife: ["Reticulated giraffe", "Gerenuk", "Leopard", "Elephant"], nearest: { course: "karen", how: "1-hour flight from Nairobi" }, signature: "The dry-country species you see nowhere else.", note: "Semi-arid northern Kenya along the Ewaso Nyiro river, with the 'Samburu special five' and some of the best leopard viewing in the country." },
    { id: "tsavo", name: "Tsavo East & West", country: "Kenya", countryId: "kenya", type: "National park", tier: "premium", bestMonths: "Jun – Oct, Jan – Feb", photo: "elephantHeadOn", wildlife: ["Red elephants", "Lion", "Wild dog"], nearest: { course: "vipingo", how: "2 hours from the coast" }, signature: "Red-dust elephants on the way to the coast.", note: "Kenya's largest park, on the road and rail line between Nairobi and Mombasa. The natural bridge between a Nairobi golf week and Vipingo Ridge." },

    { id: "serengeti", name: "Serengeti National Park", country: "Tanzania", countryId: "tanzania", type: "National park", tier: "luxury", bestMonths: "Jun – Oct, Dec – Mar", photo: "herd", wildlife: ["Great Migration", "Lion", "Cheetah", "Leopard"], nearest: { course: "kili", how: "1-hour flight from Kilimanjaro" }, signature: "The greatest wildlife stage on earth.", note: "Endless plains, two million animals on the move, and the highest density of big cats in Africa. Allow four nights and move camps with the herds." },
    { id: "ngorongoro", name: "Ngorongoro Crater", country: "Tanzania", countryId: "tanzania", type: "Conservation area", tier: "luxury", bestMonths: "Jun – Oct, Dec – Mar", photo: "rhinoBlack", wildlife: ["Black rhino", "Lion", "Elephant", "Flamingo"], nearest: { course: "kili", how: "3-hour drive from Arusha" }, signature: "A day on the crater floor.", note: "A collapsed volcano holding the densest concentration of large mammals in Africa. Stay on the rim and descend at dawn before the day visitors." },
    { id: "tarangire", name: "Tarangire National Park", country: "Tanzania", countryId: "tanzania", type: "National park", tier: "premium", bestMonths: "Jun – Oct", photo: "baobabs", wildlife: ["Elephant herds", "Baobabs", "Lion"], nearest: { course: "kili", how: "2-hour drive from Arusha" }, signature: "Elephants among the baobabs.", note: "Underrated and close to Arusha, with some of the largest elephant herds in the north and a river that draws everything in the dry season." },
    { id: "lake-manyara", name: "Lake Manyara National Park", country: "Tanzania", countryId: "tanzania", type: "National park", tier: "premium", bestMonths: "Jun – Oct", photo: "flamingos2", wildlife: ["Tree-climbing lion", "Flamingo", "Hippo"], nearest: { course: "kili", how: "2-hour drive from Arusha" }, signature: "Tree-climbing lions and a lakeshore of birds.", note: "A small, pretty park between Tarangire and the Crater, ideal for a half-day on the road to Ngorongoro." },
    { id: "ruaha", name: "Ruaha National Park", country: "Tanzania", countryId: "tanzania", type: "National park", tier: "luxury", bestMonths: "Jun – Oct", photo: "lionWalk", wildlife: ["Lion prides", "Wild dog", "Kudu", "Elephant"], nearest: { course: "kili", how: "2-hour flight from Arusha or Dar" }, signature: "Tanzania's wild south, with ten per cent of Africa's lions.", note: "Vast, remote and almost empty of other vehicles. For second-time safari-goers who want the bush to themselves." },
    { id: "nyerere", name: "Nyerere National Park (Selous)", country: "Tanzania", countryId: "tanzania", type: "National park", tier: "premium", bestMonths: "Jun – Oct", photo: "hippos", wildlife: ["Hippo", "Crocodile", "Wild dog", "Boat safari"], nearest: { course: "sea-cliff", how: "45-minute flight from Dar or Zanzibar" }, signature: "Safari by boat on the Rufiji.", note: "The largest protected area in Africa, with boat, walking and fly-camping safaris. The natural pairing with Zanzibar's golf and beach." },

    { id: "bwindi", name: "Bwindi Impenetrable Forest", country: "Uganda", countryId: "uganda", type: "National park", tier: "luxury", bestMonths: "Jun – Sep, Dec – Feb", photo: "gorillaFamily", wildlife: ["Mountain gorilla", "Forest birds"], nearest: { course: "entebbe", how: "1-hour flight from Entebbe to Kihihi" }, signature: "An hour with a gorilla family.", note: "Half the world's remaining mountain gorillas live in this ancient forest. Permits are limited and we hold an allocation for our guests." },
    { id: "queen-elizabeth", name: "Queen Elizabeth National Park", country: "Uganda", countryId: "uganda", type: "National park", tier: "premium", bestMonths: "Jun – Sep, Dec – Feb", photo: "hippo", wildlife: ["Tree-climbing lion", "Hippo", "Elephant", "Kazinga Channel"], nearest: { course: "entebbe", how: "1-hour flight from Entebbe" }, signature: "The Kazinga Channel by boat.", note: "Savanna, crater lakes and the channel between two lakes with the highest concentration of hippo in Africa. Two hours from Bwindi." },
    { id: "murchison", name: "Murchison Falls National Park", country: "Uganda", countryId: "uganda", type: "National park", tier: "premium", bestMonths: "Dec – Feb, Jun – Sep", photo: "zambeziBank", wildlife: ["Elephant", "Giraffe", "Nile crocodile", "Shoebill"], nearest: { course: "entebbe", how: "1-hour flight from Entebbe" }, signature: "The Nile forced through a seven-metre gap.", note: "Uganda's largest park, where the Nile explodes through a gorge. Boat safaris to the foot of the falls and open savanna north of the river." },
    { id: "kibale", name: "Kibale National Park", country: "Uganda", countryId: "uganda", type: "National park", tier: "premium", bestMonths: "Jun – Sep, Dec – Feb", photo: "highlands", wildlife: ["Chimpanzee", "13 primate species"], nearest: { course: "entebbe", how: "5-hour drive or flight to Kasese" }, signature: "Chimpanzee tracking in the forest.", note: "The primate capital of East Africa. A morning with a habituated chimp community pairs with Queen Elizabeth next door." },

    { id: "volcanoes", name: "Volcanoes National Park", country: "Rwanda", countryId: "rwanda", type: "National park", tier: "luxury", bestMonths: "Jun – Sep, Dec – Feb", photo: "gorilla", wildlife: ["Mountain gorilla", "Golden monkey"], nearest: { course: "kigali", how: "2.5-hour drive from Kigali" }, signature: "Gorillas on the slopes of the Virungas.", note: "Where Dian Fossey worked. The treks are shorter and gentler than Bwindi's, the lodges are the finest in the region, and Kigali's course is on the way." },
    { id: "akagera", name: "Akagera National Park", country: "Rwanda", countryId: "rwanda", type: "National park", tier: "premium", bestMonths: "Jun – Sep", photo: "hipposGrass", wildlife: ["Lion", "Rhino", "Hippo", "Elephant"], nearest: { course: "kigali", how: "2.5-hour drive from Kigali" }, signature: "A Big Five park reborn.", note: "Lakes, wetlands and savanna on the Tanzanian border, restocked with lion and rhino. A classic safari to balance the gorillas." },
    { id: "nyungwe", name: "Nyungwe Forest National Park", country: "Rwanda", countryId: "rwanda", type: "National park", tier: "premium", bestMonths: "Jun – Sep, Dec – Feb", photo: "elephantForest", wildlife: ["Chimpanzee", "Colobus", "Canopy walk"], nearest: { course: "kigali", how: "5-hour drive from Kigali" }, signature: "The canopy walk above an ancient rainforest.", note: "One of Africa's oldest forests, with chimpanzees, thirteen primate species and a tea-country drive to get there." },

    { id: "kruger", name: "Kruger National Park", country: "South Africa", countryId: "south-africa", type: "National park", tier: "premium", bestMonths: "May – Oct", photo: "lioness", wildlife: ["Big Five", "Wild dog", "Over 500 bird species"], nearest: { course: "skukuza", how: "Skukuza Golf is inside the park" }, signature: "The Big Five, and nine holes inside the park.", note: "The size of Wales and the most accessible great park in Africa. Skukuza's unfenced course is a round like no other." },
    { id: "sabi-sand", name: "Sabi Sand Game Reserve", country: "South Africa", countryId: "south-africa", type: "Private reserve", tier: "luxury", bestMonths: "May – Oct", photo: "leopard", wildlife: ["Leopard", "Lion", "Rhino", "Wild dog"], nearest: { course: "leopard-creek", how: "90 minutes by road" }, signature: "The leopard capital of Africa.", note: "Private reserve on Kruger's western boundary where leopard viewing was pioneered. Off-road tracking, night drives and the finest lodges in the country." },
    { id: "timbavati", name: "Timbavati Private Nature Reserve", country: "South Africa", countryId: "south-africa", type: "Private reserve", tier: "luxury", bestMonths: "May – Oct", photo: "lionPair", wildlife: ["White lion", "Leopard", "Elephant"], nearest: { course: "leopard-creek", how: "2 hours by road" }, signature: "The white lions of the Timbavati.", note: "Quieter than the Sabi Sand, sharing an unfenced border with Kruger and famous for its rare white lions." },
    { id: "madikwe", name: "Madikwe Game Reserve", country: "South Africa", countryId: "south-africa", type: "Game reserve", tier: "luxury", bestMonths: "May – Oct", photo: "cheetah", wildlife: ["Big Five", "Wild dog", "Cheetah"], nearest: { course: "erinvale", how: "1-hour flight from Johannesburg" }, signature: "Malaria-free Big Five, a short hop from Johannesburg.", note: "Malaria-free and family-friendly on the Botswana border, with one of the strongest wild dog populations in the country." },
    { id: "addo", name: "Addo Elephant National Park", country: "South Africa", countryId: "south-africa", type: "National park", tier: "premium", bestMonths: "Year-round", photo: "elephantReeds", wildlife: ["Elephant", "Lion", "Buffalo", "Whales offshore"], nearest: { course: "fancourt-links", how: "3-hour drive from Fancourt" }, signature: "Six hundred elephants at the end of the Garden Route.", note: "Malaria-free and an easy drive from Fancourt, with a marine section that adds whales and great white sharks to the list." },
    { id: "phinda", name: "Phinda Private Game Reserve", country: "South Africa", countryId: "south-africa", type: "Private reserve", tier: "luxury", bestMonths: "May – Oct", photo: "cheetahClose", wildlife: ["Cheetah", "Black rhino", "Leopard", "Sand forest"], nearest: { course: "leopard-creek", how: "1-hour flight from Johannesburg" }, signature: "Cheetah in the sand forest, the ocean an hour away.", note: "Seven habitats in one reserve on the KwaZulu-Natal coast, with the best cheetah viewing in the country and scuba diving at Sodwana." },

    { id: "victoria-falls-np", name: "Victoria Falls National Park", country: "Zimbabwe", countryId: "zimbabwe", type: "National park", tier: "premium", bestMonths: "Feb – Jun (full flow), Aug – Oct (clear views)", photo: "vicFallsSunset", wildlife: ["The Falls", "Rainforest", "Zambezi cruises"], nearest: { course: "elephant-hills", how: "5 minutes from Elephant Hills" }, signature: "The smoke that thunders, next to the first tee.", note: "The rainforest path along the lip of the Falls, a sunset cruise above them, and Elephant Hills Golf five minutes up the road." },
    { id: "hwange", name: "Hwange National Park", country: "Zimbabwe", countryId: "zimbabwe", type: "National park", tier: "luxury", bestMonths: "Jul – Oct", photo: "etoshaElephant", wildlife: ["Elephant herds", "Lion", "Wild dog", "Sable"], nearest: { course: "elephant-hills", how: "2-hour drive from Victoria Falls" }, signature: "Forty thousand elephants and almost no one else.", note: "Zimbabwe's largest park, with huge elephant herds at the pumped waterholes in the dry season and some of the best guides in Africa." },
    { id: "mana-pools", name: "Mana Pools National Park", country: "Zimbabwe", countryId: "zimbabwe", type: "National park", tier: "luxury", bestMonths: "Jun – Oct", photo: "zambeziBank", wildlife: ["Walking safari", "Elephant", "Wild dog", "Canoeing"], nearest: { course: "borrowdale", how: "Light aircraft from Harare or Victoria Falls" }, signature: "Walking and canoeing on the Zambezi floodplain.", note: "A World Heritage Site where you walk among elephants beneath the albida trees and canoe past hippo on the Zambezi." },

    { id: "chobe", name: "Chobe National Park", country: "Botswana", countryId: "botswana", type: "National park", tier: "premium", bestMonths: "May – Oct", photo: "zambeziElephant", wildlife: ["Elephant", "Buffalo", "Lion", "River safari"], nearest: { course: "elephant-hills", how: "90-minute road transfer from Victoria Falls" }, signature: "Africa's largest elephant population, from the water.", note: "The riverfront is the show: every afternoon by electric boat as the herds come down to drink, the 4x4 for dawn." },
    { id: "okavango", name: "Okavango Delta & Moremi", country: "Botswana", countryId: "botswana", type: "Game reserve", tier: "luxury", bestMonths: "May – Oct", photo: "okavangoAerial", wildlife: ["Leopard", "Wild dog", "Red lechwe", "Mokoro safari"], nearest: { course: "phakalane", how: "Light aircraft from Maun" }, signature: "A river that ends in the desert.", note: "The world's largest inland delta, explored by mokoro, boat and 4x4 from private concessions reached only by air. The pinnacle of exclusivity." },
    { id: "makgadikgadi", name: "Makgadikgadi Pans", country: "Botswana", countryId: "botswana", type: "National park", tier: "luxury", bestMonths: "Apr – Oct", photo: "etoshaPan", wildlife: ["Meerkat", "Zebra migration", "Salt pans"], nearest: { course: "phakalane", how: "Light aircraft from Maun" }, signature: "Quad bikes on the salt pans, meerkats at dawn.", note: "An ancient lake bed the size of Portugal. Sleep out under the stars on the pans and sit with habituated meerkats in the morning." },
    { id: "kalahari", name: "Central Kalahari Game Reserve", country: "Botswana", countryId: "botswana", type: "Game reserve", tier: "luxury", bestMonths: "Dec – Apr", photo: "cheetahGold", wildlife: ["Black-maned lion", "Cheetah", "Brown hyena"], nearest: { course: "phakalane", how: "Light aircraft from Maun" }, signature: "Black-maned lions in the green season.", note: "One of the largest reserves in the world, at its best after the rains when the pans fill and the predators follow the springbok." },

    { id: "south-luangwa", name: "South Luangwa National Park", country: "Zambia", countryId: "zambia", type: "National park", tier: "luxury", bestMonths: "Jun – Oct", photo: "lioness", wildlife: ["Walking safari", "Leopard", "Wild dog", "Hippo"], nearest: { course: "lusaka", how: "1-hour flight from Lusaka" }, signature: "The home of the walking safari.", note: "Where walking safaris were invented, with the highest leopard density in Africa and night drives still permitted. Bush camps on the river bend." },
    { id: "lower-zambezi", name: "Lower Zambezi National Park", country: "Zambia", countryId: "zambia", type: "National park", tier: "luxury", bestMonths: "Jun – Oct", photo: "mokoro", wildlife: ["Canoeing", "Elephant", "Tiger fishing", "Leopard"], nearest: { course: "lusaka", how: "40-minute flight from Lusaka" }, signature: "Canoeing past elephants on the Zambezi.", note: "Opposite Mana Pools, with canoe safaris, tiger fishing and elephants wading between the islands." },
    { id: "mosi-oa-tunya", name: "Mosi-oa-Tunya National Park", country: "Zambia", countryId: "zambia", type: "National park", tier: "premium", bestMonths: "Feb – Jun, Aug – Oct", photo: "vicBridge", wildlife: ["The Falls", "White rhino", "Zambezi cruises"], nearest: { course: "livingstone", how: "10 minutes from Livingstone Royal" }, signature: "The Falls from the Zambian side, and Livingstone's rhino.", note: "The small park that holds the Zambian side of the Falls and the country's only white rhino, walkable with a ranger." },

    { id: "etosha", name: "Etosha National Park", country: "Namibia", countryId: "namibia", type: "National park", tier: "premium", bestMonths: "May – Oct", photo: "etoshaZebra", wildlife: ["Black rhino", "Elephant", "Lion", "Floodlit waterholes"], nearest: { course: "windhoek", how: "4-hour drive from Windhoek" }, signature: "Waterholes on the edge of a salt pan.", note: "A vast white pan ringed by waterholes where everything comes to drink. The floodlit waterholes at the camps are a safari in themselves after dark." },
    { id: "sossusvlei-np", name: "Namib-Naukluft: Sossusvlei", country: "Namibia", countryId: "namibia", type: "National park", tier: "luxury", bestMonths: "Apr – Oct", photo: "deadvlei", wildlife: ["The dunes", "Oryx", "Deadvlei", "Dark skies"], nearest: { course: "rossmund", how: "4-hour drive from Swakopmund" }, signature: "The tallest dunes on earth at sunrise.", note: "Not a wildlife safari but the landscape of a lifetime: red dunes, the dead trees of Deadvlei, and the darkest skies in Africa." },
    { id: "damaraland", name: "Damaraland & Twyfelfontein", country: "Namibia", countryId: "namibia", type: "Conservancy", tier: "luxury", bestMonths: "May – Oct", photo: "loneTree", wildlife: ["Desert elephant", "Black rhino tracking", "Rock art"], nearest: { course: "rossmund", how: "4-hour drive from Swakopmund" }, signature: "Tracking desert-adapted rhino on foot.", note: "Community conservancies in the rocky north-west, with desert elephants in the dry riverbeds and the most successful rhino conservation story in Africa." },

    { id: "black-river", name: "Black River Gorges National Park", country: "Mauritius", countryId: "mauritius", type: "National park", tier: "premium", bestMonths: "May – Nov", photo: "highlands", wildlife: ["Endemic birds", "Waterfalls", "Rainforest hikes"], nearest: { course: "heritage-chateau", how: "20 minutes from the Heritage estate" }, signature: "The island's last rainforest, above the Heritage courses.", note: "Hiking trails, waterfalls and the pink pigeon and Mauritius kestrel, both brought back from near-extinction. A morning away from the course." }
  ];

  /* ---------- Rates for the trip builder (indicative, USD per person sharing) ---------- */
  S.RATES = {
    courseDay: 420,           // round, caddie, transfers and a night nearby
    premiumCourseDay: 580,    // the marquee courses
    premiumCourses: ["fancourt-links", "leopard-creek", "pearl-valley", "heritage-chateau", "ile-aux-cerfs", "kili"],
    parkNight: { premium: 760, luxury: 1180 },
    gorillaPermit: 800,       // added once per gorilla park
    gorillaParks: ["bwindi", "volcanoes"],
    stopLogistics: 220,       // transfer or light aircraft per stop
    countryChange: 260        // regional flight between countries
  };

  /* ---------- Lookups ---------- */
  S.country = function (id) { return S.COUNTRIES.filter(function (c) { return c.id === id; })[0] || null; };
  S.countryByName = function (name) { return S.COUNTRIES.filter(function (c) { return c.name === name; })[0] || null; };
  S.park = function (id) { return S.PARKS.filter(function (p) { return p.id === id; })[0] || null; };
  S.course = function (id) { return S.COURSES.filter(function (c) { return c.id === id; })[0] || null; };
  S.coursesIn = function (countryId) { var c = S.country(countryId); return c ? S.COURSES.filter(function (x) { return x.country === c.name; }) : []; };
  S.parksIn = function (countryId) { return S.PARKS.filter(function (p) { return p.countryId === countryId; }); };
})();
